# Generated by Django 5.0.6 on 2024-06-12 15:08

import api.models.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photos",
            fields=[
                (
                    "image_hash",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("image_size", models.BigIntegerField(default=0)),
                ("original_image", models.ImageField(upload_to="originals")),
                ("optimized_image", models.ImageField(upload_to="optimized")),
                ("thumbnail", models.ImageField(upload_to="thumbnails")),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                (
                    "captions_json",
                    models.JSONField(blank=True, db_index=True, null=True),
                ),
                (
                    "geolocation_json",
                    models.JSONField(blank=True, db_index=True, null=True),
                ),
                ("exif_json", models.JSONField(blank=True, null=True)),
                ("exif_gps_lat", models.FloatField(blank=True, null=True)),
                ("exif_gps_lon", models.FloatField(blank=True, null=True)),
                ("exif_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "search_captions",
                    models.TextField(blank=True, db_index=True, null=True),
                ),
                (
                    "search_location",
                    models.TextField(blank=True, db_index=True, null=True),
                ),
                ("rating", models.IntegerField(db_index=True, default=0)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("hidden", models.BooleanField(db_index=True, default=False)),
                ("video", models.BooleanField(default=False)),
                ("video_length", models.TextField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        default=None,
                        on_delete=models.SET(api.models.user.get_deleted_user),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
