# Generated by Django 5.0.6 on 2024-06-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_image_size_photos_size_photos_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="date_of_death",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="notes",
            field=models.TextField(null=True),
        ),
    ]
