# Generated by Django 5.0.6 on 2024-06-15 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_person_date_of_birth_person_date_of_death_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photos",
            name="dominant_color",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="save_metadata_to_disk",
            field=models.TextField(
                choices=[
                    ("OFF", "Off"),
                    ("MEDIA_FILE", "Media File"),
                    ("SIDECAR_FILE", "Sidecar File"),
                ],
                default="OFF",
            ),
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "hash",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("path", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "Image"),
                            (2, "Video"),
                            (3, "Metadata File e.g. XMP"),
                            (4, "Raw File"),
                            (5, "Unknown"),
                        ],
                    ),
                ),
                ("missing", models.BooleanField(default=False)),
                ("embedded_media", models.ManyToManyField(to="api.file")),
            ],
        ),
        migrations.AddField(
            model_name="photos",
            name="files",
            field=models.ManyToManyField(to="api.file"),
        ),
        migrations.AlterField(
            model_name="photos",
            name="original_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_photo",
                to="api.file",
            ),
        ),
    ]
