# Generated by Django 5.0.6 on 2024-06-23 11:04

import api.models.user
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_photos_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="albums",
            name="album_name",
        ),
        migrations.AddField(
            model_name="albums",
            name="cover_photo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="album_user",
                to="api.photos",
            ),
        ),
        migrations.AddField(
            model_name="albums",
            name="created_on",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name="albums",
            name="favorited",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="albums",
            name="title",
            field=models.CharField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="AlbumThing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=512)),
                (
                    "thing_type",
                    models.CharField(db_index=True, max_length=512, null=True),
                ),
                ("favorited", models.BooleanField(db_index=True, default=False)),
                ("photo_count", models.IntegerField(default=0)),
                (
                    "cover_photos",
                    models.ManyToManyField(
                        related_name="album_thing_cover_photos", to="api.photos"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=None,
                        on_delete=models.SET(api.models.user.get_deleted_user),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("photos", models.ManyToManyField(to="api.photos")),
            ],
        ),
        migrations.CreateModel(
            name="AlbumDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, db_index=True, max_length=512, null=True
                    ),
                ),
                ("date", models.DateField(db_index=True, null=True)),
                ("favorited", models.BooleanField(db_index=True, default=False)),
                ("location", models.JSONField(blank=True, db_index=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        default=None,
                        on_delete=models.SET(api.models.user.get_deleted_user),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("photos", models.ManyToManyField(to="api.photos")),
            ],
            options={
                "unique_together": {("owner", "date")},
            },
        ),
        migrations.CreateModel(
            name="AlbumPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=512)),
                ("geolocation_level", models.IntegerField(db_index=True, null=True)),
                ("favorited", models.BooleanField(db_index=True, default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        default=None,
                        on_delete=models.SET(api.models.user.get_deleted_user),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("photos", models.ManyToManyField(to="api.photos")),
            ],
            options={
                "unique_together": {("title", "owner")},
            },
        ),
        migrations.AddConstraint(
            model_name="albumthing",
            constraint=models.UniqueConstraint(
                fields=("title", "thing_type", "owner"), name="unique AlbumThing"
            ),
        ),
    ]
