# Generated by Django 5.0.6 on 2024-06-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_albums_album_name_albums_cover_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='semantic_search_topk',
        ),
    ]
