# Generated by Django 5.0.6 on 2024-06-28 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_user_semantic_search_topk"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="scan_directory",
            field=models.CharField(
                db_index=True, default=django.utils.timezone.now, max_length=512
            ),
            preserve_default=False,
        ),
    ]
