# Generated by Django 5.0.6 on 2024-06-29 14:27

import api.models.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_scan_directory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_on', models.DateTimeField(db_index=True)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lon', models.FloatField(blank=True, null=True)),
                ('favorited', models.BooleanField(db_index=True, default=False)),
                ('owner', models.ForeignKey(default=None, on_delete=models.SET(api.models.user.get_deleted_user), to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(to='api.photos')),
            ],
            options={
                'unique_together': {('timestamp', 'owner')},
            },
        ),
    ]
