# Generated by Django 5.0.6 on 2024-06-30 01:56

import api.models.user
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_job_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('created_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('favorited', models.BooleanField(db_index=True, default=False)),
                ('cover_photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums_user', to='api.photos')),
                ('owner', models.ForeignKey(default=None, on_delete=models.SET(api.models.user.get_deleted_user), to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(to='api.photos')),
            ],
            options={
                'unique_together': {('title', 'owner')},
            },
        ),
    ]
