# Generated by Django 5.0.6 on 2024-07-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_albumuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='aspect_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
