# Generated by Django 5.0.6 on 2024-07-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_photos_aspect_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_scale',
            field=models.FloatField(default=1),
        ),
    ]
